#!/usr/bin/env python3
"""
init_ai_coding.py — Scaffold a Chromium-style AI Coding infrastructure for any repository.

Usage:
    python3 init_ai_coding.py [--dir /path/to/repo] [--project-name "My Project"] [--force] [--dry-run]

This script creates the agents/ directory structure with layered prompts,
skills, knowledge base, eval cases, and project templates.
"""

import argparse
import os
import sys
from pathlib import Path
from datetime import datetime


# ---------------------------------------------------------------------------
# Template content for every file we scaffold
# ---------------------------------------------------------------------------

AI_POLICY_TEMPLATE = """# AI Usage Policy

> **Core Principle**: AI is a tool, not an author. Every human developer is
> fully responsible for every line of code they submit.

## Rules

| Rule | Requirement | Violation Consequence |
|------|-------------|-----------------------|
| **Self-Review Obligation** | Review and understand ALL code before submitting. Ensure correctness, design, security, and style. | Submitting code you don't understand → loss of commit privileges. Repeat → account suspension. |
| **Original Work Declaration** | You must declare all submitted code as your own original work, regardless of AI assistance. | Violation of project code of conduct. |
| **Human Replies to Humans** | If an AI-generated change receives human feedback, a human must reply. | Violation of project code of conduct. |

## Recommended Practices

- Document AI tool usage in change descriptions (e.g., include the prompt used).
- When driving AI with a design document, commit the design document alongside the generated code.
- Use AI to accelerate understanding, not to avoid understanding.

## Scope

This policy applies to all AI-assisted contributions including but not limited to:
code generation, test generation, refactoring suggestions, documentation, and
code review assistance.

---

*This file was auto-generated by repo-init. Customize it for your team's needs.*
"""


COMMON_MINIMAL_TEMPLATE = """# Common Minimal Instructions (Layer 1)

> This is the foundational instruction layer shared by all developers.
> It defines the non-negotiable basics. Higher layers build on top of this.

## Build

- **Always confirm the build directory and target before building.**
- Never guess build configuration. Ask the developer if unsure.
- Prefer project-standard build commands (e.g., `make`, `bazel build`, `cargo build`).

## Test

- Use the project's standard test runner.
- Do NOT manually invoke the build step before running tests — the test runner handles it.
- Always run tests relevant to the files you modified.

## Coding

- **Stay on task**: Do not fix unrelated TODOs or code health issues unless asked.
- **Comments explain "why", never "what"**: Code should be self-documenting for the "what."
- Follow the project's existing code style and patterns.
- When in doubt, match the surrounding code's conventions.

## Pre-Submit

- Run the project's formatting and linting tools before submitting.
- Only fix issues your changes introduced — do not fix pre-existing warnings.
- Verify your changes don't break existing tests.

## Cross-Language Bindings (if applicable)

- Follow the project's established patterns for cross-language bindings (JNI, FFI, WASM, etc.).
- Never invent new binding conventions without consulting the team.

---

*Customize this file with your project's specific build, test, and coding conventions.*
"""


COMMON_WORKFLOW_TEMPLATE = """# Common Workflow (Layer 2)

> Standard workflow for all code editing tasks. This layer is loaded for
> every AI-assisted development session.
>
> This layer builds on `common.minimal.md` (Layer 1). Ensure the minimal
> instructions are also loaded in your AI agent configuration.

## Standard Workflow — 8 Steps

### Step 1: Deep Code Understanding (Mandatory First Step — Never Skip)

```
1a. Locate Core Files
    → Identify all files relevant to the task.

1b. Complete Audit
    → Read the FULL source of each relevant file.
    → Summarize control flow, data flow, and ownership semantics.

1c. State Understanding
    → Present your understanding to the developer.
    → Wait for confirmation before proceeding.

1d. Anti-Patterns to Avoid:
    ✗ Never guess behavior from function names — read the implementation.
    ✗ Always check at least one call site to understand usage patterns.
```

### Step 2: Write Code

- Do ONLY what the task requires. No scope creep.
- Follow the patterns and conventions found in Step 1.

### Step 3: Write / Update Tests

- Prefer adding test cases to existing test files.
- Create new test files only when no appropriate test file exists.
- Cover both happy path and error cases.

### Step 4: Build

- Build only the targets affected by your changes.
- Use the project's standard build commands.

### Step 5: Fix Build Errors

- For each error, read at least one new file to understand the context.
- Find and understand ALL related files before attempting a fix.
- Check if the same error appeared earlier in the conversation.
- **Never make speculative fixes.**

### Step 6: Run Tests

- Run all tests affected by your changes.
- Also run a broader test suite to catch regressions.

### Step 7: Fix Test Failures

- Read failing test output carefully.
- Understand WHY the test fails before fixing it.
- Fix the code, not the test (unless the test itself is wrong).

### Step 8: Iterate

- Loop Steps 4–7 until all builds pass and all tests pass.
- Report final status to the developer.

---

*Customize the number of steps and their details to match your project's workflow.*
"""


KNOWLEDGE_BASE_TEMPLATE = """# Knowledge Base — Agentic RAG

> **Core Principle: Consult, then Answer**
>
> You MUST NOT answer from general knowledge alone. Before answering any
> query, you MUST first consult the relevant documents in this repository.

## How It Works

This file is a **static routing table**. When the developer asks a question or
gives a task, check the task features below and read the indicated documents
before responding.

## Programming Pattern Routing

| Detected Feature | Action |
|-----------------|--------|
| Involves IPC / cross-process communication | Read the project's IPC documentation first |
| Involves async operations or threading | Read `docs/threading.md` or equivalent |
| Involves callbacks / promises / futures | Read the project's async patterns doc |
| Modifies core framework / engine code | Read the relevant style guide and architecture doc |
| Involves database / storage layer | Read the data layer documentation |
| Involves network / API layer | Read the networking documentation |

## Feature Development Routing

| Detected Feature | Action |
|-----------------|--------|
| Involves user preferences / settings | Read `docs/prefs.md` or equivalent |
| Involves metrics / analytics | Read `docs/metrics.md` or equivalent |
| Involves build configuration | Read the build system documentation |
| Involves UI components | Read the UI framework documentation |
| Involves security / permissions | Read the security documentation |

## Debugging Routing

| Error Type | Action |
|-----------|--------|
| "Header not found" / "Module not found" | 1. Verify dependencies in build config 2. Verify include paths 3. Regenerate build files |
| Linker error ("undefined symbol") | 1. Check dependencies 2. Check symbol visibility 3. Verify build target configuration |
| Visibility / access error | Add the depending target to the visibility list |
| Test flakiness | Read the project's testing best practices doc |

## When Static Routing Is Not Enough

If the task doesn't match any rule above:
1. Search the project's `docs/` directory for relevant files.
2. Read the most relevant document(s).
3. Then answer based on what you found.

---

*Add your project-specific routing rules here. The more specific the rules,
the better the AI will perform.*
"""


TEMPLATE_DEFAULT_TEMPLATE = """# Default Platform Template

> This is the default platform template. Create additional templates for
> specific platforms (e.g., `desktop.md`, `android.md`, `web.md`) as needed.

## Before Starting Any Task

Read these files first (if they exist):

- `docs/architecture.md` — Project architecture overview
- `docs/coding-style.md` — Coding style guide
- `docs/testing.md` — Testing conventions

## Build Targets

- **Main target**: (define your main build target)
- **Test target**: (define your test target)
- **Lint target**: (define your lint target)

## Test Execution

- Run all tests: (define command)
- Run specific test: (define command)
- Run with coverage: (define command)

---

*Customize this template for your project's specific build system and targets.*
"""


TEMPLATE_README = """# Platform Templates

## What Are Platform Templates?

Platform templates provide platform-specific context to the AI agent. They
ensure the AI doesn't make incorrect assumptions about platform details.

## Creating a New Template

1. Create a new file: `templates/<platform>.md`
2. Reference it from your project's `AGENTS.md` or `GEMINI.md`:

```
@agents/prompts/common.md
@agents/prompts/templates/<platform>.md
```

## Template Contents

Each template should define:
- **Prerequisite reading**: Documents the AI must read before starting
- **Build targets**: Platform-specific build targets
- **Test execution**: How to run tests on this platform
- **Naming conventions**: Platform-specific naming rules
- **Common pitfalls**: Things the AI should avoid on this platform

## Example Templates

- `desktop.md` — Desktop application development
- `web.md` — Web frontend development
- `mobile.md` — Mobile application development
- `backend.md` — Backend / server development
"""


EVAL_README = """# Eval: AI Agent Evaluation Test Suite

## Purpose

This directory contains evaluation test cases for the AI Agent's behavior.
When prompts are modified, run these evals to ensure the AI's behavior hasn't
regressed.

## Structure

Each eval case is a subdirectory containing:

```
<eval-name>/
├── prompt.md    # Simulated user input (the task)
└── eval.md      # Expected outcomes and assertions
```

## Creating a New Eval Case

1. Create a new subdirectory: `eval/<case-name>/`
2. Write `prompt.md`: A realistic user request
3. Write `eval.md`: Expected outcomes (files changed, commands run, etc.)

## Running Evals

Currently, evals are run manually by giving the `prompt.md` content to the AI
and comparing its behavior against `eval.md`. As the project matures, consider
automating with a framework like promptfoo.

## Example Cases to Create

- `add-test-coverage` — AI adds unit tests for a function
- `fix-broken-test` — AI diagnoses and fixes a failing test
- `generate-change-description` — AI generates a change description from a diff
- `code-refactor` — AI refactors a specific code pattern
- `feature-flag` — AI adds a new feature flag
"""


EVAL_EXAMPLE_PROMPT = """# Eval: Example Case — Add Test Coverage

## Simulated User Request

I have a function called `calculateDiscount` in `src/pricing/discount.py`.
It takes a `price` (float) and a `customer_type` (string) and returns the
discounted price. Can you add unit tests covering:
1. Regular customer (no discount)
2. VIP customer (20% discount)
3. Employee (50% discount)
4. Invalid customer type (should raise ValueError)
5. Negative price (should raise ValueError)
"""


EVAL_EXAMPLE_EVAL = """# Eval Criteria: Add Test Coverage

## Expected Outcomes

### Files Changed
- `tests/pricing/test_discount.py` (modified or created)

### Content Assertions
- File MUST contain a test class or test functions for `calculateDiscount`
- MUST cover all 5 test cases listed in the prompt
- MUST use the project's standard test framework
- MUST NOT modify the source file `src/pricing/discount.py`

### Process Assertions
- AI should read `src/pricing/discount.py` before writing tests
- AI should read existing test files to match conventions
- AI should run the tests after writing them
"""


COMMANDS_README = """# Task Prompts (Shortcut Commands)

## What Are Task Prompts?

Task prompts are pre-written prompts for common development tasks. They
encapsulate the complete steps for a specific operation, ensuring consistency
and saving time.

## Creating a New Command

1. Create a new file: `commands/<command-name>.md`
2. Write the prompt with clear, step-by-step instructions
3. Reference it from your project configuration or invoke it directly

## Suggested Commands

| Command | Purpose |
|---------|---------|
| `/project:fix-review-comments` | Automatically address code review feedback |
| `/project:gen-tests` | Generate unit tests for changed code |
| `/project:change-description` | Generate a change description from diff |
| `/project:pre-upload-checklist` | Run pre-submission checks |
| `/project:disable-test` | Safely disable a failing test |
| `/project:search-code` | Search for code patterns across the repo |
"""


SKILLS_README = """# Skills: On-Demand Expert Modules

## What Are Skills?

Skills are **expert modules** that activate only when the user's request is
relevant. Unlike prompts (which are always loaded), skills are **on-demand** —
the AI agent loads a `SKILL.md` file only when it determines the task matches
the skill's domain.

## Creating a New Skill

1. Create a new directory: `skills/<skill-name>/`
2. Create `SKILL.md` inside it with:
   - **Description**: What the skill does and when it activates
   - **Checklist**: Step-by-step instructions for the task
   - **References**: Links to relevant documentation

## Skill Template

```markdown
# Skill: <skill-name>

## Description
What this skill does.

## Activation
When the user's request involves <trigger conditions>, load this skill.

## Checklist
1. Step one
2. Step two
3. ...

## References
- Link to relevant docs
```

## Suggested Starter Skills

| Skill | Purpose |
|-------|---------|
| `feature-flag` | Add/remove feature flags |
| `test-generation` | Generate unit/integration tests |
| `code-refactor` | Safe refactoring patterns |
| `metrics` | Add analytics/metrics tracking |
| `documentation` | Generate or update documentation |
| `debugging` | Systematic debugging procedures |
| `security-review` | Security review checklist |
| `performance` | Performance optimization patterns |
"""


SKILL_EXAMPLE_TEMPLATE = """# Skill: example-skill

## Description
This is an example skill template. Replace it with a real skill for your project.

## Activation
When the user's request involves [describe trigger conditions], load this skill.

## Checklist

1. **Understand the context**
   - Read all relevant files
   - Confirm understanding with the developer

2. **Plan the changes**
   - List the files that need modification
   - Describe the approach

3. **Implement**
   - Make the changes
   - Follow project coding conventions

4. **Test**
   - Write or update tests
   - Run the test suite

5. **Verify**
   - Run pre-submission checks
   - Confirm everything passes

## Anti-Patterns to Avoid

- Don't skip the understanding phase
- Don't make changes not requested by the task
- Don't ignore existing code conventions

## References
- Link to relevant project documentation
"""


EXTENSIONS_README = """# MCP Extensions

## What Are MCP Extensions?

MCP (Model Context Protocol) extensions provide the AI agent with external
tool capabilities beyond the built-in set. They connect the AI to external
services, APIs, and data sources.

## Setting Up an MCP Extension

1. Install the MCP server (e.g., via npm, pip, or binary)
2. Configure it in your AI tool's MCP settings
3. The AI agent will automatically discover and use available tools

## Suggested Extensions

| Extension | Purpose |
|-----------|---------|
| `code-search` | Search code across the repository |
| `documentation-search` | Search external documentation |
| `build-info` | Query build configuration and status |
| `issue-tracker` | Query and update issue tracker |
| `git-history` | Search git history and blame |

## Project-Specific Extensions

Add your project-specific MCP extensions here as needed.
"""


PROJECTS_README = """# Projects: AI-Driven Large-Scale Engineering

## What Are Projects?

Unlike Skills (which handle single tasks), Projects are **large-scale
engineering initiatives** with long-running goals. They include complete
project structures with SKILL.md files, reference documentation, Python
scripts, and automation pipelines.

## When to Create a Project

- Large-scale code migrations
- Automated code health initiatives
- Systematic refactoring campaigns
- Multi-phase feature rollouts

## Project Structure

```
projects/<project-name>/
├── SKILL.md           # Project instructions and checklist
├── README.md          # Project overview and goals
├── references/        # Reference documentation
├── scripts/           # Automation scripts
└── tests/             # Project-specific tests
```

## Example Projects

| Project | Goal |
|---------|------|
| `code-health` | Automated code quality improvements |
| `modernization` | Systematic code modernization |
| `deprecation` | Remove deprecated APIs |
"""


# ---------------------------------------------------------------------------
# File mapping: relative path → template content
# ---------------------------------------------------------------------------

FILE_MAP = {
    "agents/ai_policy.md": AI_POLICY_TEMPLATE,
    "agents/prompts/common.minimal.md": COMMON_MINIMAL_TEMPLATE,
    "agents/prompts/common.md": COMMON_WORKFLOW_TEMPLATE,
    "agents/prompts/knowledge_base.md": KNOWLEDGE_BASE_TEMPLATE,
    "agents/prompts/templates/default.md": TEMPLATE_DEFAULT_TEMPLATE,
    "agents/prompts/templates/README.md": TEMPLATE_README,
    "agents/prompts/eval/README.md": EVAL_README,
    "agents/prompts/eval/example/prompt.md": EVAL_EXAMPLE_PROMPT,
    "agents/prompts/eval/example/eval.md": EVAL_EXAMPLE_EVAL,
    "agents/prompts/commands/README.md": COMMANDS_README,
    "agents/skills/README.md": SKILLS_README,
    "agents/skills/example-skill/SKILL.md": SKILL_EXAMPLE_TEMPLATE,
    "agents/extensions/README.md": EXTENSIONS_README,
    "agents/projects/README.md": PROJECTS_README,
}

# Directory to copy entirely (the understand skill + scripts)
# This is handled separately from FILE_MAP since it's a directory tree.
UNDERSTAND_SKILL_SOURCE = Path(__file__).parent.parent / "agents-understand"


def create_file(path: Path, content: str, dry_run: bool = False, force: bool = False) -> tuple[bool, bool]:
    """Write content to a file, creating parent directories as needed.
    Returns (written, existed) tuple."""
    existed = path.exists()
    if existed and not force:
        print(f"  ⚠  SKIP (exists): {path}")
        return (False, existed)
    if dry_run:
        action = "OVERWRITE" if existed else "CREATE"
        print(f"  ○  WOULD {action}: {path}")
        return (True, existed)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    action = "OVERWRITTEN" if existed else "CREATED"
    print(f"  ✓  {action}: {path}")
    return (True, existed)


def customize_content(content: str, project_name: str) -> str:
    """Replace placeholders in template content."""
    return content.replace("{project_name}", project_name)


def init_repo(target_dir: Path, project_name: str, dry_run: bool = False, force: bool = False) -> None:
    """Scaffold the full AI Coding infrastructure."""
    print(f"\n{'='*60}")
    print(f"  AI Coding Infrastructure Initialization")
    print(f"  Project: {project_name}")
    print(f"  Target:  {target_dir.resolve()}")
    if force:
        print(f"  Force:   ON (existing files will be overwritten)")
    print(f"{'='*60}\n")

    if dry_run:
        print("  DRY RUN — no files will be written\n")

    created = 0
    overwritten = 0
    skipped = 0

    for rel_path, template in FILE_MAP.items():
        full_path = target_dir / rel_path
        content = customize_content(template, project_name)
        written, existed = create_file(full_path, content, dry_run, force)
        if written:
            if existed:
                overwritten += 1
            else:
                created += 1
        else:
            skipped += 1

    print(f"\n{'='*60}")
    if dry_run:
        print(f"  Summary: {created} would create, {overwritten} would overwrite, {skipped} would skip")
    else:
        parts = []
        if created:
            parts.append(f"{created} created")
        if overwritten:
            parts.append(f"{overwritten} overwritten")
        if skipped:
            parts.append(f"{skipped} skipped")
        print(f"  Summary: {', '.join(parts)}")
    print(f"{'='*60}\n")

    # Copy the understand skill directory
    _copy_understand_skill(target_dir, dry_run, force)

    if not dry_run:
        _print_next_steps()
        _run_validation(target_dir)


def _copy_understand_skill(target_dir: Path, dry_run: bool = False, force: bool = False) -> None:
    """Copy the understand skill directory (agents-understand) into the target repo."""
    import shutil

    if not UNDERSTAND_SKILL_SOURCE.exists():
        return

    dest_skill = target_dir / "agents" / "skills" / "understand"
    dest_skill_dash = target_dir / "agents" / "skills" / "understand-dashboard"
    dest_scripts = target_dir / "scripts" / "understand"

    if dry_run:
        for d in [dest_skill, dest_scripts]:
            if d.exists() and not force:
                print(f"  ⚠  SKIP (exists): {d}")
            else:
                print(f"  ○  WOULD COPY: {d}")
        return

    # Copy understand skill
    _copy_dir(UNDERSTAND_SKILL_SOURCE / "skills" / "understand", dest_skill, force)
    _copy_dir(UNDERSTAND_SKILL_SOURCE / "skills" / "understand-dashboard", dest_skill_dash, force)

    # Copy understand scripts
    _copy_dir(UNDERSTAND_SKILL_SOURCE / "scripts" / "understand", dest_scripts, force)

    # Copy chromium_docs.py (standalone script in the skill's scripts/ dir)
    _copy_file(Path(__file__).parent / "chromium_docs.py", target_dir / "scripts" / "chromium_docs.py", force)

    # Copy references/ directory
    _copy_dir(Path(__file__).parent.parent / "references", target_dir / "agents" / "references", force)


def _copy_file(src: Path, dest: Path, force: bool) -> None:
    """Copy a single file, handling existing destinations."""
    import shutil
    if not src.exists():
        return
    if dest.exists():
        if force:
            dest.unlink()
            shutil.copy2(src, dest)
            print(f"  ✓  OVERWRITTEN: {dest}")
        else:
            print(f"  ⚠  SKIP (exists): {dest}")
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        print(f"  ✓  COPIED: {dest}")


def _copy_dir(src: Path, dest: Path, force: bool) -> None:
    """Copy a directory, handling existing destinations."""
    import shutil
    if not src.exists():
        return
    if dest.exists():
        if force:
            shutil.rmtree(dest)
            shutil.copytree(src, dest)
            print(f"  ✓  OVERWRITTEN: {dest}")
        else:
            print(f"  ⚠  SKIP (exists): {dest}")
    else:
        shutil.copytree(src, dest)
        print(f"  ✓  COPIED: {dest}")


def _print_next_steps() -> None:
    """Print post-initialization steps."""
    print("  Next steps:")
    print("  1. Run: python3 scripts/understand/generate_context.py .  — analyze the codebase")
    print("  2. Read .understand/context.md  — review the analysis")
    print("  3. Edit agents/ai_policy.md — define your team's AI rules")
    print("  4. Edit agents/prompts/common.minimal.md — use build/test commands from context")
    print("  5. Edit agents/prompts/knowledge_base.md — add doc routes from context")
    print("  6. Edit agents/prompts/templates/default.md — use build targets from context")
    print("  7. Create platform templates in agents/prompts/templates/")
    print("  8. Replace example-skill in agents/skills/ with real skills")
    print("  9. Run: python3 scripts/understand/build_graph.py . --output .understand/knowledge-graph.json")
    print("  7. Build eval cases in agents/prompts/eval/")
    print()


def _run_validation(target_dir: Path) -> None:
    """Validate the scaffolded structure and warn about issues."""
    print("  Validation:")

    critical_files = [
        "agents/ai_policy.md",
        "agents/prompts/common.minimal.md",
        "agents/prompts/common.md",
        "agents/prompts/knowledge_base.md",
    ]

    important_files = [
        "agents/skills/understand/SKILL.md",
        "agents/skills/understand-dashboard/SKILL.md",
        "scripts/understand/scan_project.py",
        "scripts/understand/generate_context.py",
        "scripts/understand/build_graph.py",
        "scripts/understand/launch_dashboard.py",
        "scripts/chromium_docs.py",
    ]

    ok = True
    for rel in critical_files:
        path = target_dir / rel
        if path.exists():
            print(f"    ✓  {rel}")
        else:
            print(f"    ✗  MISSING: {rel}")
            ok = False

    # Check important (non-critical) files
    for rel in important_files:
        path = target_dir / rel
        if path.exists():
            print(f"    ✓  {rel}")
        else:
            print(f"    ⚠  MISSING: {rel}")

    # Warn about placeholder content
    example_skill = target_dir / "agents/skills/example-skill/SKILL.md"
    if example_skill.exists():
        content = example_skill.read_text(encoding="utf-8")
        if "example-skill" in content and "This is an example" in content:
            print(f"    ⚠  agents/skills/example-skill/SKILL.md is still a placeholder — replace or remove")

    if ok:
        print(f"\n    All critical files present. Ready for customization.\n")
    else:
        print(f"\n    Some critical files are missing. Re-run with --force to regenerate.\n")


def main():
    parser = argparse.ArgumentParser(
        description="Initialize a repository with AI Coding infrastructure"
    )
    parser.add_argument(
        "--dir",
        default=".",
        help="Target repository root directory (default: current directory)",
    )
    parser.add_argument(
        "--project-name",
        default="My Project",
        help="Name of the project (used in template placeholders)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be created without writing files",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files (default: skip existing)",
    )
    args = parser.parse_args()

    target = Path(args.dir)
    if not target.is_dir():
        print(f"Error: {target} is not a directory.", file=sys.stderr)
        sys.exit(1)

    init_repo(target, args.project_name, args.dry_run, args.force)


if __name__ == "__main__":
    main()
